services:
  db:
    image: postgres:17
    container_name: sexshop-db
    environment:
      POSTGRES_USER: sexshopuser
      POSTGRES_PASSWORD: sexshoppass
      POSTGRES_DB: sexshopdb
    ports:
      - "5432:5432"
    volumes:
      - sexshop-data:/var/lib/postgresql/data

volumes:
  sexshop-data: